### ISSUE TITLE
Failed to load the discord-send-embed-code-to-webhook package

### ISSUE THREAD

**Issue by tytytytytyt5** [XXCoreRangerX/discord-send-embed-code-to-webhook#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.56.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Home
**Thrown From**: [discord-send-embed-code-to-webhook](https://github.com/XXCoreRangerX/discord-send-embed-code-to-webhook) package 3.1.0

### Stack Trace

Failed to load the discord-send-embed-code-to-webhook package

```
At Cannot find module 'hastebin-gen'
Require stack:
- C:\Users\User\.atom\packages\discord-send-embed-code-to-webhook\lib\discord-send-embed-code-to-webhook.js
- C:\Users\User\AppData\Local\atom\app-1.56.0\resources\app.asar\static\index.html

Error: Cannot find module 'hastebin-gen'
Require stack:
- C:\Users\User\.atom\packages\discord-send-embed-code-to-webhook\lib\discord-send-embed-code-to-webhook.js
- C:\Users\User\AppData\Local\atom\app-1.56.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:157820)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:149153)
    at /packages/discord-send-embed-code-to-webhook/lib/discord-send-embed-code-to-webhook.js:4:18)
    at /packages/discord-send-embed-code-to-webhook/lib/discord-send-embed-code-to-webhook.js:198:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:1:802769)
    at requireModule (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:14:1126115)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:3496608)
    at ~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:3483148
    at Package.measure (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:3481948)
    at Package.load (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:3482721)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:383596)
    at PackageManager.loadPackage (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:382324)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:384896)
    at ~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:911030
    at r (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:905636)
    at n (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:14:1125438)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:14:1125644)
    at ChildProcess.emit (events.js:223:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

### Commands

```
  3x -1:25.1.0 core:select-all (input.hidden-input)
     -1:08.0 core:backspace (input.hidden-input)
  2x -0:38.3.0 core:select-all (input.hidden-input)
```

### Non-Core Packages

```
discord-send-code-to-webhook 1.2.1 
discord-send-embed-code-to-webhook 3.1.0 
```

**Comment by XXCoreRangerX** [comment]
Hello, the issues you're having happen when `node.js` and/or it's packages are not installed.

As stated in README - make sure to install `node.js` and required packages (`discord.js` and `hastebin-gen`). You also don’t need both `discord-send-code-to-webhook` and `discord-send-embed-code-to-webhook` for the package to work, they are two separate packages.

You can download node.js from it's [website](https://nodejs.org/en/download/).

After that open Windows CMD to install the required plugins using npm:
```console
npm install discord.js
npm install hastebin-gen
```

**Comment by Lebedev21** [comment]
> Hello, the issues you're having happen when `node.js` and/or it's packages are not installed.
> 
> As stated in README - make sure to install `node.js` and required packages (`discord.js` and `hastebin-gen`). You also don’t need both `discord-send-code-to-webhook` and `discord-send-embed-code-to-webhook` for the package to work, they are two separate packages.
> 
> You can download node.js from it's [website](https://nodejs.org/en/download/).
> 
> After that open Windows CMD to install the required plugins using npm:
> 
> ```
> npm install discord.js
> npm install hastebin-gen
> ```

Are you supposed to install the npm packages in: C:\Users\(user)\.atom\packages\discord-send-embed-code-to-webhook\lib ?
I did that, the package installed normally but now it won't send anything to my webhook.

**Comment by XXCoreRangerX** [comment]
You don't have to install them in a specific directory. You only need to type these commands in the command line.

Toggle developer tools (`View > Developer > Toggle Developer Tools`) and check if there's anything appearing in Console when you try to send text.

If you haven't - make sure to specify the webhook's URL in package settings.

Check if keybindings of packages overlap. There's some packages which use <kbd>Ctrl</kbd><kbd>Q</kbd> keybind by default, blocking it from other packages. To verify that, go to the Keybindings tab in Atom settings.

Also, a known issue right now is that whenever one tries to send text from an untitled file (or file that doesn't have a file extension) it will not work. I'm working on that right now.
